/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import dao.SQLServerProvider;
import java.sql.ResultSet;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Nhan
 */
public class DangNhap extends javax.swing.JFrame {
    private String tenDN;
    private String matKhau;
    private boolean kqDN;
    private String loaidn;

    public void setLoaidn(String loaidn) {
        this.loaidn = loaidn;
    }
    
    public String getTenDN() {
        return tenDN;
    }

    public void setTenDN(String tenDN) {
        this.tenDN = tenDN;
    }

    public String getMatKhau() {
        return matKhau;
    }

    public void setMatKhau(String matKhau) {
        this.matKhau = matKhau;
    }

    public boolean isKqDN() {
        return kqDN;
    }

    public void setKqDN(boolean kqDN) {
        this.kqDN = kqDN;
    }
    
    /**
     * Creates new form DangNhap
     */
    public DangNhap() {
        initComponents();
        this.setSize(600, 500);
        this.setLocationRelativeTo(null);
        this.setTitle("Đăng Nhập");
        this.setResizable(false);
        this.setDefaultCloseOperation(EXIT_ON_CLOSE);
        ImageIcon mainscreen = new ImageIcon("src\\image\\banner.jpg");
        this.lbBanner.setIcon(mainscreen);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DNGROUP = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        UserName = new javax.swing.JTextField();
        pass = new javax.swing.JPasswordField();
        nvbtn = new javax.swing.JRadioButton();
        qlbtn = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnDN = new javax.swing.JButton();
        btnThoat = new javax.swing.JButton();
        lbBanner = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 51));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("ĐĂNG NHẬP");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(80, 30, 460, 40);

        UserName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UserNameActionPerformed(evt);
            }
        });
        jPanel1.add(UserName);
        UserName.setBounds(210, 110, 320, 40);
        jPanel1.add(pass);
        pass.setBounds(210, 180, 320, 40);

        DNGROUP.add(nvbtn);
        nvbtn.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        nvbtn.setForeground(new java.awt.Color(0, 255, 204));
        nvbtn.setText("Nhân Viên");
        nvbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nvbtnActionPerformed(evt);
            }
        });
        jPanel1.add(nvbtn);
        nvbtn.setBounds(100, 280, 137, 37);

        DNGROUP.add(qlbtn);
        qlbtn.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        qlbtn.setForeground(new java.awt.Color(0, 255, 204));
        qlbtn.setText("Quản Lý");
        qlbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                qlbtnActionPerformed(evt);
            }
        });
        jPanel1.add(qlbtn);
        qlbtn.setBounds(350, 280, 119, 37);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 255, 204));
        jLabel1.setText("Tên Đăng Nhập");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(30, 110, 160, 40);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 255, 204));
        jLabel3.setText("PASSWORD");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(30, 180, 160, 40);

        btnDN.setForeground(new java.awt.Color(0, 255, 204));
        btnDN.setText("ĐĂNG NHẬP");
        btnDN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDNActionPerformed(evt);
            }
        });
        jPanel1.add(btnDN);
        btnDN.setBounds(60, 370, 201, 43);

        btnThoat.setForeground(new java.awt.Color(0, 255, 204));
        btnThoat.setText("THOÁT");
        btnThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThoatActionPerformed(evt);
            }
        });
        jPanel1.add(btnThoat);
        btnThoat.setBounds(340, 370, 215, 43);
        jPanel1.add(lbBanner);
        lbBanner.setBounds(0, 0, 600, 510);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 600, 510);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void qlbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_qlbtnActionPerformed
        // TODO add your handling code here:
        this.setLoaidn("quanly");
    }//GEN-LAST:event_qlbtnActionPerformed

    private void UserNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UserNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UserNameActionPerformed

    private void btnThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThoatActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnThoatActionPerformed

    private void nvbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nvbtnActionPerformed
        // TODO add your handling code here:
        this.setLoaidn("nhanvien");
    }//GEN-LAST:event_nvbtnActionPerformed

    private void btnDNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDNActionPerformed
        // TODO add your handling code here:
        try{
            tenDN = UserName.getText();
            matKhau = pass.getText();
            SQLServerProvider provider = new SQLServerProvider();
            provider.Open();
            if(loaidn == null)
            {
                JOptionPane.showMessageDialog(null, "VUI LÒNG CHỌN QUYỀN ĐĂNG NHẬP");
            }
            else if(loaidn.equalsIgnoreCase("quanly"))
            {
                 String sqlSelect = "Select * from QUANLY where TENDN = '"+ tenDN+"' AND MK = '" + matKhau +"'";
                 ResultSet rs = provider.executeQuery(sqlSelect);
                 while(rs.next())
                 {
                    this.setKqDN(true);
                 }
                 if (isKqDN())
                 {
                    JOptionPane.showMessageDialog(null, "Đăng Nhập thành công");
                    QuanLy_CaPhe guiQL = new QuanLy_CaPhe();
                    guiQL.setLoaitaikhoan("admin");
                    guiQL.setLogin(true);
                    guiQL.Run();
                    this.dispose();
                    guiQL.setVisible(true);
                }
                else
                {
                    JOptionPane.showMessageDialog(null, "Đăng nhập không thành công");
                    UserName.setText("");
                    pass.setText("");
                }
            }
            else if (loaidn.equalsIgnoreCase("nhanvien"))
            {
                 String sqlSelect = "Select * from NGUOIDUNG where TENDN = '"+ tenDN+"' AND MK = '" + matKhau +"'";
                 ResultSet rs = provider.executeQuery(sqlSelect);
                 while(rs.next())
                 {
                    this.setKqDN(true);
                 }
                 if (isKqDN())
                 {
                    JOptionPane.showMessageDialog(null, "Đăng Nhập thành công");
                    QuanLy_CaPhe guiQL = new QuanLy_CaPhe();
                    guiQL.setLoaitaikhoan("nhanvien");
                    guiQL.setLogin(true);
                    guiQL.Run();
                    this.dispose();
                    guiQL.setVisible(true);
                }
                else
                {
                    JOptionPane.showMessageDialog(null, "Đăng nhập không thành công");
                    UserName.setText("");
                    pass.setText("");
                }
            }
            
        }catch(Exception e)
        {
            System.out.println(e);
        }
    }//GEN-LAST:event_btnDNActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DangNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DangNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DangNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DangNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DangNhap().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup DNGROUP;
    private javax.swing.JTextField UserName;
    private javax.swing.JButton btnDN;
    private javax.swing.JButton btnThoat;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbBanner;
    private javax.swing.JRadioButton nvbtn;
    private javax.swing.JPasswordField pass;
    private javax.swing.JRadioButton qlbtn;
    // End of variables declaration//GEN-END:variables
}
