/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;
import dao.NhapKhoDAO;
import dao.SQLServerProvider;
import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import pojo.NhapKho;
/**
 *
 * @author Admin
 */
public class TimKiemNhapKho extends javax.swing.JDialog {

    /**
     * Creates new form TimKiemNhapKho
     */
    CallableStatement callableStatement;
    Connection con;
    ResultSet rs;
    DefaultTableModel dtm = new DefaultTableModel();
    public TimKiemNhapKho(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        dtm.addColumn("Mã nhập kho");
        dtm.addColumn("Mã nguyên liệu");
        dtm.addColumn("Ngày nhập");
        dtm.addColumn("Số lượng");
        dtm.addColumn("Thành tiền");
        tbTim.setModel(dtm);
        ketnoiCSDL();
        loadNhapKho();
        
    }
    public void ketnoiCSDL(){
        String server = "LAPTOP-1LO8U7LN\\SQLEXPRESS";
        String user ="sa";
        String password = "nguyen114814";
        String databasename = "DEAN_JAVA";
        try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String url = "jdbc:sqlserver://"+server
                    + ":1433;databaseName="+databasename
                    +";user="+user
                    +";password="+password;
            con = DriverManager.getConnection(url);
        } catch (Exception e) {
            System.out.println(e);
        }
        
    }
    public void loadNhapKho()
    {
        try {
            ArrayList<NhapKho> dsnk = NhapKhoDAO.layDsNhapKho();
            dtm.setRowCount(0);
            for(NhapKho nk : dsnk)
            {
                Vector<Object> vec = new Vector<Object>();
                vec.add(nk.getMaNhapKho());
                vec.add(nk.getMaNguyenLieu());
                vec.add(nk.getNgayNhap());
                vec.add(nk.getSoLuong());
                vec.add(nk.getThanhTien());
                dtm.addRow(vec);
            }
            tbTim.setModel(dtm);
        } catch (Exception ex) {
            System.out.println(ex);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbTim = new javax.swing.JTable();
        tfTim = new javax.swing.JTextField();
        btnTim = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        tbTim.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbTim.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tbTimMouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tbTim);

        btnTim.setText("Tìm");
        btnTim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(layout.createSequentialGroup()
                .addGap(117, 117, 117)
                .addComponent(tfTim, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnTim)
                .addContainerGap(118, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfTim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTim))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tbTimMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbTimMouseReleased
        // TODO add your handling code here:
        int r = tbTim.getSelectedRow();
        int c = tbTim.getSelectedColumn();
        if(tbTim.isEditing())
        {
            tbTim.getCellEditor(r,c).cancelCellEditing();
        }
    }//GEN-LAST:event_tbTimMouseReleased

    private void btnTimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimActionPerformed
        // TODO add your handling code here:
        SQLServerProvider provider = new SQLServerProvider();
        if(tfTim.getText().length() > 0)
        {
            try {
                provider.Open();
                callableStatement = con.prepareCall("{call TIMKIEMNHAPKHO(?)}");
                callableStatement.setString(1, tfTim.getText());
                rs = callableStatement.executeQuery();
                dtm.setRowCount(0);
                tbTim.setModel(dtm);
                while(rs.next())
                {
                    NhapKho nk = new NhapKho();
                    nk.setMaNhapKho(rs.getString("MANHAPKHO"));
                    nk.setMaNguyenLieu(rs.getString("MANL"));
                    nk.setNgayNhap(rs.getDate("NGAYNHAP"));
                    nk.setSoLuong(rs.getInt("SOLUONG"));
                    nk.setThanhTien(rs.getInt("THANHTIEN"));
                    Vector<Object> vec = new Vector<Object>();
                    vec.add(nk.getMaNhapKho());
                    vec.add(nk.getMaNguyenLieu());
                    vec.add(nk.getNgayNhap());
                    vec.add(nk.getSoLuong());
                    vec.add(nk.getThanhTien());
                    dtm.addRow(vec);
                }
                
                tbTim.setModel(dtm);
            } catch (SQLException ex) {
                System.out.println(ex);
            }
            
        }
        else
        {
            loadNhapKho();
        }
        provider.Close();
    }//GEN-LAST:event_btnTimActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TimKiemNhapKho.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TimKiemNhapKho.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TimKiemNhapKho.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TimKiemNhapKho.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                TimKiemNhapKho dialog = new TimKiemNhapKho(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnTim;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbTim;
    private javax.swing.JTextField tfTim;
    // End of variables declaration//GEN-END:variables
}
