/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import dao.XuatKhoDAO;
import dao.SQLServerProvider;
import java.sql.CallableStatement;
import java.sql.Date;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import pojo.XuatKho;

/**
 *
 * @author Admin
 */
public class Xuat_Kho extends javax.swing.JDialog {

    /**
     * Creates new form NhapKho
     */
    DefaultTableModel dtm = new DefaultTableModel();
    CallableStatement callableStatement;
    public Xuat_Kho(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setTitle("Nhập kho");
        this.setResizable(false);
        dtm.addColumn("Mã xuất kho");
        dtm.addColumn("Mã nguyên liệu");
        dtm.addColumn("Ngày xuất");
        dtm.addColumn("Số lượng");
        dtm.addColumn("Thành tiền");
        tbXuatKho.setModel(dtm);
        loadXuatKho();
    }
    public void loadXuatKho()
    {
        try {
            ArrayList<XuatKho> dsxk = XuatKhoDAO.layDsXuatKho();
            dtm.setRowCount(0);
            for(XuatKho nk : dsxk)
            {
                Vector<Object> vec = new Vector<Object>();
                vec.add(nk.getMaXuatKho());
                vec.add(nk.getMaNguyenLieu());
                vec.add(nk.getNgayXuat());
                vec.add(nk.getSoLuong());
                vec.add(nk.getThanhTien());
                dtm.addRow(vec);
            }
            tbXuatKho.setModel(dtm);
        } catch (Exception ex) {
            System.out.println(ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbXuatKho = new javax.swing.JTable();
        btnThem = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnTimKiem = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        tfMaXuatKho = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tfMaNL = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tfNgayXuat = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        tfSoLuong = new javax.swing.JTextField();
        tfThanhTien = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 0, 204));
        jLabel1.setText("XUẤT KHO");

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        tbXuatKho.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbXuatKho.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbXuatKhoMouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tbXuatKhoMouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tbXuatKho);

        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        btnSua.setText("Sửa");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        btnTimKiem.setText("Tìm kiếm");
        btnTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimKiemActionPerformed(evt);
            }
        });

        jLabel2.setText("Mã xuất kho");

        jLabel3.setText("Mã nguyên liệu:");

        jLabel4.setText("Ngày xuất");

        jLabel5.setText("Số lượng:");

        jLabel13.setText("Thành tiền:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 680, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(274, 274, 274)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42)
                        .addComponent(btnSua, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(btnTimKiem))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel13))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tfMaXuatKho, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE)
                            .addComponent(tfMaNL)
                            .addComponent(tfThanhTien))
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 77, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tfNgayXuat)
                            .addComponent(tfSoLuong, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel1)
                .addGap(32, 32, 32)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tfMaXuatKho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(tfNgayXuat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tfMaNL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(tfSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addComponent(tfThanhTien, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnXoa)
                    .addComponent(btnSua)
                    .addComponent(btnTimKiem)
                    .addComponent(btnThem))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        // TODO add your handling code here:
        if(tfMaXuatKho.getText().length() == 0)
        {
            JOptionPane.showMessageDialog(null, "Mã nhập kho không được để trống","Lỗi",JOptionPane.ERROR_MESSAGE);
            return;
        }
        String ma = tfMaXuatKho.getText().trim();
        if(XuatKhoDAO.ktMa(ma))
        {
            int n = JOptionPane.showConfirmDialog(null, "Bạn có chắc chắn muốn update?","Thông báo",JOptionPane.YES_NO_OPTION, JOptionPane.INFORMATION_MESSAGE);
            if(n == JOptionPane.YES_OPTION)
            {
                XuatKho xk = new XuatKho();
                xk.setMaXuatKho(tfMaXuatKho.getText().trim());
                xk.setMaNguyenLieu(tfMaNL.getText().trim());
                xk.setNgayXuat(Date.valueOf(tfNgayXuat.getText().trim()));
                xk.setSoLuong(Integer.parseInt(tfSoLuong.getText()));
                xk.setThanhTien(Integer.parseInt(tfThanhTien.getText()));
                boolean kq = XuatKhoDAO.capNhatXuatKho(xk);
                if(kq)
                {
                    JOptionPane.showMessageDialog(null, "Cập nhật thành công","Thông báo",JOptionPane.INFORMATION_MESSAGE);
                    loadXuatKho();
                }
                else
                {
                    JOptionPane.showMessageDialog(null, "Cập nhật thất bại","Lỗi",JOptionPane.ERROR_MESSAGE);
                }
            }
        }
        else
        {
            JOptionPane.showMessageDialog(null, "Mã này không tồn tại nên không thể update","Lỗi",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnSuaActionPerformed

    private void tbXuatKhoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbXuatKhoMouseClicked
        // TODO add your handling code here:
        int a = tbXuatKho.getSelectedRow();
        tfMaXuatKho.setText(tbXuatKho.getValueAt(a, 0).toString());
        tfMaNL.setText(tbXuatKho.getValueAt(a, 1).toString());
        tfNgayXuat.setText(tbXuatKho.getValueAt(a, 2).toString());
        tfSoLuong.setText(tbXuatKho.getValueAt(a, 3).toString());
        tfThanhTien.setText(tbXuatKho.getValueAt(a, 4).toString());
    }//GEN-LAST:event_tbXuatKhoMouseClicked

    private void tbXuatKhoMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbXuatKhoMouseReleased
        // TODO add your handling code here:
        int r = tbXuatKho.getSelectedRow();
        int c = tbXuatKho.getSelectedColumn();
        if(tbXuatKho.isEditing())
        {
            tbXuatKho.getCellEditor(r,c).cancelCellEditing();
        }
    }//GEN-LAST:event_tbXuatKhoMouseReleased

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        // TODO add your handling code here:
        if(tfMaXuatKho.getText().length() == 0)
        {
            JOptionPane.showMessageDialog(null, "Mã nhập kho không được để trống","Lỗi",JOptionPane.ERROR_MESSAGE);
            return;
        }
        if(XuatKhoDAO.ktMa(tfMaXuatKho.getText().trim()))
        {
            JOptionPane.showMessageDialog(null, "Mã này đã tồn tại nên không thể thêm","Lỗi",JOptionPane.ERROR_MESSAGE);
            return;
        }
        XuatKho xk = new XuatKho();
        xk.setMaXuatKho(tfMaXuatKho.getText().trim());
        xk.setMaNguyenLieu(tfMaNL.getText().trim());
        xk.setNgayXuat(Date.valueOf(tfNgayXuat.getText().trim()));
        xk.setSoLuong(Integer.parseInt(tfSoLuong.getText()));
        xk.setThanhTien(Integer.parseInt(tfThanhTien.getText()));
        int n = JOptionPane.showConfirmDialog(null, "Bạn có chắc chắn muốn thêm không?","Thông báo",JOptionPane.YES_NO_OPTION,JOptionPane.INFORMATION_MESSAGE);
        if(n == JOptionPane.YES_OPTION)
        {
            
            boolean kq = XuatKhoDAO.themXuatKho(xk);
            if(kq)
            {
                JOptionPane.showMessageDialog(null, "Thêm thành công","Thông báo",JOptionPane.INFORMATION_MESSAGE);
                loadXuatKho();
            }
            else
            {
                JOptionPane.showMessageDialog(null, "Thêm thất bại","Lỗi",JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // TODO add your handling code here:
        if(tbXuatKho.getSelectedRow() == -1)
        {
            JOptionPane.showMessageDialog(null, "Phải chọn 1 dòng để xóa","Lỗi",JOptionPane.ERROR_MESSAGE);
            return;
        }
        String ma = tfMaXuatKho.getText();
        int n = JOptionPane.showConfirmDialog(null, "Bạn có chắc chắn muốn xóa?","Thông báo",JOptionPane.YES_NO_OPTION, JOptionPane.INFORMATION_MESSAGE);
        if(n == JOptionPane.YES_OPTION)
        {
            boolean kq = XuatKhoDAO.xoaXuatKho(ma);
            if(kq)
            {
                JOptionPane.showMessageDialog(null, "Xóa thành công","Thông báo",JOptionPane.INFORMATION_MESSAGE);
                loadXuatKho();
            }
            else
            {
                JOptionPane.showMessageDialog(null, "Xóa thất bại","Lỗi",JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimKiemActionPerformed
        // TODO add your handling code here:
        TimKiemXuatKho a = new TimKiemXuatKho(null, true);
        a.setVisible(true);
    }//GEN-LAST:event_btnTimKiemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Xuat_Kho.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Xuat_Kho.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Xuat_Kho.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Xuat_Kho.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Xuat_Kho dialog = new Xuat_Kho(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnTimKiem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbXuatKho;
    private javax.swing.JTextField tfMaNL;
    private javax.swing.JTextField tfMaXuatKho;
    private javax.swing.JTextField tfNgayXuat;
    private javax.swing.JTextField tfSoLuong;
    private javax.swing.JTextField tfThanhTien;
    // End of variables declaration//GEN-END:variables
}
